//! Frozen format vectors.
//!
//! These tests read files that were written once and committed. Their job is to
//! fail when the on-disk format changes, so that it cannot change by accident.
//!
//! # What is frozen, and why it is this and not the other thing
//!
//! The obvious approach — encrypt a fixed input and compare the bytes — does not
//! work here, and should not: every nonce in the format is fresh randomness, so
//! encrypting the same file twice deliberately produces different bytes.
//!
//! What matters is the other direction anyway. The guarantee users need is that
//! **a vault written by an older build stays readable**, and that is exactly
//! what these tests check: committed ciphertext, decrypted with a known key,
//! compared against known plaintext.
//!
//! The parts of the format that *are* deterministic — key derivation, sub-key
//! derivation, filename encryption, directory placement — are frozen as exact
//! bytes in `derivations.txt`, because a change to any of them makes every
//! existing vault unopenable.
//!
//! # When one of these fails
//!
//! Do not regenerate the vectors to make the test pass. The failure is the
//! safety net working. Ask first whether the format change was intended; if it
//! was, update `docs/FORMAT_SPEC.md`, provide a migration or bump the format
//! version, and say so in the commit message. See `CONTRIBUTING.md`.

// Integration tests are a separate crate, so they do not inherit the crate-root
// allowances that unit tests get. A panicking assertion here is a failing test,
// which is exactly what is wanted, and every size in this file is a fixed
// constant rather than something that could truncate.
#![allow(
    clippy::unwrap_used,
    clippy::expect_used,
    clippy::panic,
    clippy::cast_possible_truncation,
    reason = "test code: a panic is a failing test, and all sizes here are fixed constants"
)]

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use cv_crypto::aead::AeadAlgorithm;
use cv_crypto::hierarchy::{MasterSeed, SubKey, derive_subkey};
use cv_crypto::kdf::{self, Argon2Params};
use cv_crypto::secret::Key32;
use cv_crypto::siv;
use cv_crypto::slot::SlotKind;
use cv_format::config;
use cv_format::consts::CHUNK_PLAINTEXT_LEN;
use cv_format::content::open_chunk;
use cv_format::dirmap::dir_path;
use cv_format::names::{self, EntryKind};
use cv_format::{FileHeader, FileMode};

// The same fixed inputs the generator used. Test values, not secrets.
const CONTENT_KEY: [u8; 32] = [0x01; 32];
const NAMES_KEY: [u8; 32] = [0x02; 32];
const MAC_KEY: [u8; 32] = [0x03; 32];
const MASTER_SEED: [u8; 32] = [0x04; 32];
const VAULT_ID: [u8; 16] = [0x05; 16];
const SALT: [u8; 16] = [0x06; 16];
const DIR_ID: [u8; 16] = [0x07; 16];
const PASSWORD: &[u8] = b"vector password";
const PLAINTEXT_LEN: usize = 70_000;

fn vectors_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/vectors")
}

fn read(name: &str) -> Vec<u8> {
    let path = vectors_dir().join(name);
    std::fs::read(&path).unwrap_or_else(|error| {
        panic!(
            "could not read the frozen vector {}: {error}\n\
             Vectors are committed to the repository; they are not generated by the test run.",
            path.display()
        )
    })
}

/// The plaintext inside `file.cvf`: a repeating pattern, so a chunk read from
/// the wrong offset shows up as a mismatch rather than as plausible data.
fn expected_plaintext() -> Vec<u8> {
    (0..PLAINTEXT_LEN)
        .map(|i| u8::try_from(i % 251).unwrap_or(0))
        .collect()
}

fn cheap_params() -> Argon2Params {
    Argon2Params::new(
        Argon2Params::MIN_MEMORY_KIB,
        Argon2Params::MIN_ITERATIONS,
        Argon2Params::MIN_PARALLELISM,
    )
    .expect("the minimum is within bounds")
}

fn derivations() -> HashMap<String, String> {
    let text = String::from_utf8(read("derivations.txt")).expect("derivations.txt is not UTF-8");
    text.lines()
        .filter(|line| !line.trim().is_empty() && !line.starts_with('#'))
        .filter_map(|line| line.split_once(" = "))
        .map(|(key, value)| (key.trim().to_owned(), value.trim().to_owned()))
        .collect()
}

fn hex(bytes: &[u8]) -> String {
    use std::fmt::Write as _;
    bytes.iter().fold(String::new(), |mut acc, byte| {
        let _ = write!(acc, "{byte:02x}");
        acc
    })
}

/// The central compatibility guarantee: a file written by an earlier build is
/// still readable, header, metadata and every chunk.
#[test]
fn a_committed_encrypted_file_still_decrypts() {
    let bytes = read("file.cvf");
    let content_key = Key32::new(CONTENT_KEY);

    let (header, header_len) =
        FileHeader::open(&bytes, &content_key).expect("the frozen file no longer parses");

    assert_eq!(header.algorithm, AeadAlgorithm::Aes256Gcm);
    assert_eq!(header.mode, FileMode::Live);
    assert_eq!(header.plain_size, PLAINTEXT_LEN as u64);

    // Metadata must survive too: dropping a field silently would lose a user's
    // timestamps and tags on every rewrite.
    assert_eq!(header.metadata.mtime, Some(1_770_000_000));
    assert_eq!(header.metadata.ctime, Some(1_769_000_000));
    assert_eq!(header.metadata.mode, Some(0o644));
    assert_eq!(header.metadata.exec, Some(false));
    assert!(header.metadata.versioned);
    assert_eq!(header.metadata.tags, ["work", "2026"]);
    assert_eq!(
        header.metadata.note.as_deref(),
        Some("frozen format vector")
    );
    assert_eq!(header.metadata.ext.as_deref(), Some("bin"));

    let stored_chunk = (CHUNK_PLAINTEXT_LEN + 12 + 16) as usize;
    let body = &bytes[usize::try_from(header_len).unwrap()..];

    let recovered: Vec<u8> = body
        .chunks(stored_chunk)
        .enumerate()
        .flat_map(|(index, piece)| {
            open_chunk(&header, index as u64, piece)
                .unwrap_or_else(|error| panic!("chunk {index} no longer decrypts: {error}"))
        })
        .collect();

    assert_eq!(recovered.len(), PLAINTEXT_LEN);
    assert_eq!(
        recovered,
        expected_plaintext(),
        "the decrypted contents changed"
    );
}

/// A vault configuration written by an earlier build must still open with the
/// same password, and must still authenticate.
#[test]
fn a_committed_vault_configuration_still_unlocks() {
    let bytes = read("vault.cvconf");

    let unlocked = config::unlock(&bytes, SlotKind::Password, PASSWORD)
        .expect("the frozen vault configuration no longer unlocks");

    assert_eq!(unlocked.seed, MasterSeed::from_key(Key32::new(MASTER_SEED)));
    assert_eq!(unlocked.config.vault_id, VAULT_ID);
    assert_eq!(unlocked.config.created, 1_770_000_000);
    assert_eq!(unlocked.config.algorithm, AeadAlgorithm::Aes256Gcm);
    assert!(!unlocked.config.sealed);
    assert_eq!(unlocked.config.slots.len(), 1);
    assert_eq!(unlocked.config.slots[0].label, "vector password slot");
}

#[test]
fn the_wrong_password_still_fails_on_the_committed_vault() {
    let bytes = read("vault.cvconf");
    assert!(config::unlock(&bytes, SlotKind::Password, b"not the password").is_err());
}

/// Argon2id parameters, the algorithm, and the derivation itself. A change to
/// any of them locks every user out of every vault.
#[test]
fn key_derivation_is_unchanged() {
    let expected = derivations();
    let kek = kdf::derive_kek(PASSWORD, &SALT, cheap_params()).expect("derivation failed");
    assert_eq!(
        hex(kek.expose()),
        expected["kek"],
        "Argon2id now produces a different key: every existing vault would refuse every password"
    );
}

/// The HKDF labels are part of the format. Changing one silently retires a
/// sub-key and makes everything encrypted under it unreadable.
#[test]
fn subkey_derivation_is_unchanged() {
    let expected = derivations();
    let seed = MasterSeed::from_key(Key32::new(MASTER_SEED));

    for (subkey, name) in [
        (SubKey::Content, "content"),
        (SubKey::Names, "names"),
        (SubKey::Mac, "mac"),
        (SubKey::Audit, "audit"),
        (SubKey::Meta, "meta"),
    ] {
        let derived = derive_subkey(&seed, &VAULT_ID, subkey).expect("derivation failed");
        assert_eq!(
            hex(derived.expose()),
            expected[&format!("subkey.{name}")],
            "the {name} sub-key changed: everything encrypted under it becomes unreadable"
        );
    }
}

/// Filename encryption is deterministic by design, so its output is frozen
/// exactly. If it changes, every file in every vault is at a name nothing looks
/// for any more.
#[test]
fn filename_encryption_is_unchanged() {
    let expected = derivations();
    let names_key = Key32::new(NAMES_KEY);

    let ciphertext = siv::seal(&names_key, &DIR_ID, b"invoice.pdf").expect("sealing failed");
    assert_eq!(hex(&ciphertext), expected["siv.invoice"]);

    let stored =
        names::encode(&names_key, &DIR_ID, "invoice.pdf", EntryKind::File).expect("encode failed");
    assert_eq!(
        stored.file_name, expected["name.invoice"],
        "the on-disk filename changed: existing files would be unreachable"
    );
}

/// Directory placement is derived, not stored. If the derivation changes, every
/// directory in every vault moves and nothing can find its contents.
#[test]
fn directory_placement_is_unchanged() {
    let expected = derivations();
    let path = dir_path(&Key32::new(MAC_KEY), &DIR_ID).expect("placement failed");
    assert_eq!(
        path, expected["dirpath"],
        "directory placement changed: every directory in every vault moves"
    );
}

/// A guard on the guard. If the vector files were ever emptied or replaced with
/// placeholders, the tests above could pass vacuously.
#[test]
fn the_vector_files_are_present_and_plausible() {
    assert!(
        read("file.cvf").len() > PLAINTEXT_LEN,
        "file.cvf is too small to hold the plaintext"
    );
    assert!(
        read("vault.cvconf").len() > 100,
        "vault.cvconf is implausibly small"
    );

    let expected = derivations();
    assert_eq!(
        expected.len(),
        9,
        "derivations.txt does not have all its entries"
    );
    for (key, value) in &expected {
        assert!(!value.is_empty(), "{key} has no value");
    }
}
